ALTER TABLE startup
ADD COLUMN IF NOT EXISTS "founderfullname" VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS "founderemail" VARCHAR(255) NOT NULL UNIQUE,
ADD COLUMN IF NOT EXISTS "foundersocials" jsonb;
