networks:
  dev:


services:
  invest_app:
    build:
      context: .
    container_name: invest_app
    depends_on:
      - postgres
    environment:
      DB_HOST: invest_postgres
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
#      REDIS_HOST:
#      REDIS_PASSWORD:
    ports:
      - "8080:8080"
    networks:
      - dev

#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - invest_app
#    networks:
#      - dev

  postgres:
    image: postgres:latest
    container_name: invest_postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U {$DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - dev


#  redis:
#    image: redis:latest
#    container_name: invest_redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/var/lib/redis/data
#    command: [ "redis-server", "--requirepass", "ricliznedokyrill" ]
#    networks:
#      - dev

#  elasticsearch:
#    mem_limit: 4g
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=true
#      - ES_JAVA_OPTS=-Xms2g -Xmx2g
#    ports:
#      - "9200:9200"
#    volumes:
#      - es_data:/var/lib/elasticsearch/data
#    networks:
#      - dev

volumes:
   postgres_data:
#   redis_data:
#  es_data:
