definitions:
  authModel.RequestSignInPayload:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  authModel.RequestSignUpPayload:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      middleName:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - firstName
    - lastName
    - middleName
    - password
    type: object
info:
  contact: {}
  description: This is a sample server for demonstrating JWT with Swagger.
  title: HaveIdea
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Вход в систему
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authModel.RequestSignInPayload'
      produces:
      - application/json
      responses:
        "200":
          description: JWT токен
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: sign-in
      tags:
      - Authorization
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Регистрация в системе
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authModel.RequestSignUpPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: sign-up
      tags:
      - Authorization
  /profile/:
    get:
      consumes:
      - application/json
      description: Посмотреть СВОЙ профиль
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: getProfile
      tags:
      - Profile
  /startup/create:
    post:
      consumes:
      - application/json
      description: Создать новый стартап
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: createStartUp
      tags:
      - StartUp
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
